
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COEFICIENTE DOSPUNTOS GUION NUMERO PNUMERO PUNTOYCOMA\n            fichero : coeficiente range_values\n            \n            coeficiente : COEFICIENTE PUNTOYCOMA\n            \n            range_values : range_value range_values \n                    | range_value\n            \n            range_value : PNUMERO DOSPUNTOS COEFICIENTE GUION COEFICIENTE PUNTOYCOMA\n            '
    
_lr_action_items = {'COEFICIENTE':([0,9,11,],[3,10,12,]),'$end':([1,4,5,8,13,],[0,-1,-4,-3,-5,]),'PNUMERO':([2,5,7,13,],[6,6,-2,-5,]),'PUNTOYCOMA':([3,12,],[7,13,]),'DOSPUNTOS':([6,],[9,]),'GUION':([10,],[11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'fichero':([0,],[1,]),'coeficiente':([0,],[2,]),'range_values':([2,5,],[4,8,]),'range_value':([2,5,],[5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> fichero","S'",1,None,None,None),
  ('fichero -> coeficiente range_values','fichero',2,'p_fichero','parser_testing.py',15),
  ('coeficiente -> COEFICIENTE PUNTOYCOMA','coeficiente',2,'p_coeficiente','parser_testing.py',21),
  ('range_values -> range_value range_values','range_values',2,'p_range_values','parser_testing.py',26),
  ('range_values -> range_value','range_values',1,'p_range_values','parser_testing.py',27),
  ('range_value -> PNUMERO DOSPUNTOS COEFICIENTE GUION COEFICIENTE PUNTOYCOMA','range_value',6,'p_range_value','parser_testing.py',38),
]
