
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COEFICIENTE DOSPUNTOS END NEXT PNUMERO PUNTOYCOMA\n            fichero : values END\n            \n            values : value_exec NEXT values \n                    | value_exec\n            \n            value_exec : neuron_value PUNTOYCOMA value_exec\n                        | neuron_value PUNTOYCOMA\n            \n            neuron_value : PNUMERO DOSPUNTOS COEFICIENTE\n            '
    
_lr_action_items = {'PNUMERO':([0,7,8,],[5,5,5,]),'$end':([1,6,],[0,-1,]),'END':([2,3,8,10,11,],[6,-3,-5,-2,-4,]),'NEXT':([3,8,11,],[7,-5,-4,]),'PUNTOYCOMA':([4,12,],[8,-6,]),'DOSPUNTOS':([5,],[9,]),'COEFICIENTE':([9,],[12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'fichero':([0,],[1,]),'values':([0,7,],[2,10,]),'value_exec':([0,7,8,],[3,3,11,]),'neuron_value':([0,7,8,],[4,4,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> fichero","S'",1,None,None,None),
  ('fichero -> values END','fichero',2,'p_fichero','parser_exec.py',14),
  ('values -> value_exec NEXT values','values',3,'p_values','parser_exec.py',20),
  ('values -> value_exec','values',1,'p_values','parser_exec.py',21),
  ('value_exec -> neuron_value PUNTOYCOMA value_exec','value_exec',3,'p_value_exec','parser_exec.py',29),
  ('value_exec -> neuron_value PUNTOYCOMA','value_exec',2,'p_value_exec','parser_exec.py',30),
  ('neuron_value -> PNUMERO DOSPUNTOS COEFICIENTE','neuron_value',3,'p_neuron_value','parser_exec.py',39),
]
