
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND CNUMERO COEFICIENTE DOSPUNTOS IDENT IF IGUAL NUMERO PNUMERO PROPOSICIONES PUNTOYCOMA REGLAS THEN\n            fichero : PROPOSICIONES propositions REGLAS rules\n            \n            propositions : propositions proposition \n                         | proposition\n            \n            proposition : text DOSPUNTOS PNUMERO IGUAL COEFICIENTE PUNTOYCOMA\n                        | text PUNTOYCOMA\n            \n            text : text IDENT \n                 | IDENT\n            \n            rules : rules rule\n                  | rule\n            \n            rule : IF PNUMERO THEN PNUMERO DOSPUNTOS CNUMERO IGUAL COEFICIENTE PUNTOYCOMA \n                 | IF PNUMERO andunion THEN PNUMERO DOSPUNTOS CNUMERO IGUAL COEFICIENTE PUNTOYCOMA\n            \n            andunion : AND PNUMERO andunion \n                     | AND PNUMERO\n            '
    
_lr_action_items = {'PROPOSICIONES':([0,],[2,]),'$end':([1,12,13,16,36,38,],[0,-1,-9,-8,-10,-11,]),'IDENT':([2,3,4,5,6,8,10,11,26,],[6,6,-3,11,-7,-2,-5,-6,-4,]),'REGLAS':([3,4,8,10,26,],[7,-3,-2,-5,-4,]),'DOSPUNTOS':([5,6,11,23,28,],[9,-7,-6,27,31,]),'PUNTOYCOMA':([5,6,11,22,34,37,],[10,-7,-6,26,36,38,]),'IF':([7,12,13,16,36,38,],[14,14,-9,-8,-10,-11,]),'PNUMERO':([9,14,19,21,24,],[15,17,23,25,28,]),'IGUAL':([15,30,33,],[18,32,35,]),'THEN':([17,20,25,29,],[19,24,-13,-12,]),'AND':([17,25,],[21,21,]),'COEFICIENTE':([18,32,35,],[22,34,37,]),'CNUMERO':([27,31,],[30,33,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'fichero':([0,],[1,]),'propositions':([2,],[3,]),'proposition':([2,3,],[4,8,]),'text':([2,3,],[5,5,]),'rules':([7,],[12,]),'rule':([7,12,],[13,16,]),'andunion':([17,25,],[20,29,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> fichero","S'",1,None,None,None),
  ('fichero -> PROPOSICIONES propositions REGLAS rules','fichero',4,'p_fichero','parser.py',14),
  ('propositions -> propositions proposition','propositions',2,'p_propositions','parser.py',20),
  ('propositions -> proposition','propositions',1,'p_propositions','parser.py',21),
  ('proposition -> text DOSPUNTOS PNUMERO IGUAL COEFICIENTE PUNTOYCOMA','proposition',6,'p_proposition','parser.py',29),
  ('proposition -> text PUNTOYCOMA','proposition',2,'p_proposition','parser.py',30),
  ('text -> text IDENT','text',2,'p_text','parser.py',39),
  ('text -> IDENT','text',1,'p_text','parser.py',40),
  ('rules -> rules rule','rules',2,'p_rules','parser.py',48),
  ('rules -> rule','rules',1,'p_rules','parser.py',49),
  ('rule -> IF PNUMERO THEN PNUMERO DOSPUNTOS CNUMERO IGUAL COEFICIENTE PUNTOYCOMA','rule',9,'p_rule','parser.py',54),
  ('rule -> IF PNUMERO andunion THEN PNUMERO DOSPUNTOS CNUMERO IGUAL COEFICIENTE PUNTOYCOMA','rule',10,'p_rule','parser.py',55),
  ('andunion -> AND PNUMERO andunion','andunion',3,'p_andunion','parser.py',60),
  ('andunion -> AND PNUMERO','andunion',2,'p_andunion','parser.py',61),
]
