
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COEFICIENTE COMA DOSPUNTOS GUION PNUMERO PUNTOYCOMA\n            fichero : results\n            \n            results : results result \n                         | result\n            \n            result : ci GUION PNUMERO PUNTOYCOMA\n            \n            ci : ci COMA PNUMERO DOSPUNTOS COEFICIENTE\n                | PNUMERO DOSPUNTOS COEFICIENTE\n            '
    
_lr_action_items = {'PNUMERO':([0,2,3,6,7,8,13,],[5,5,-3,-2,10,11,-4,]),'$end':([1,2,3,6,13,],[0,-1,-3,-2,-4,]),'GUION':([4,12,15,],[7,-6,-5,]),'COMA':([4,12,15,],[8,-6,-5,]),'DOSPUNTOS':([5,11,],[9,14,]),'COEFICIENTE':([9,14,],[12,15,]),'PUNTOYCOMA':([10,],[13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'fichero':([0,],[1,]),'results':([0,],[2,]),'result':([0,2,],[3,6,]),'ci':([0,2,],[4,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> fichero","S'",1,None,None,None),
  ('fichero -> results','fichero',1,'p_fichero','parser_training.py',14),
  ('results -> results result','results',2,'p_results','parser_training.py',20),
  ('results -> result','results',1,'p_results','parser_training.py',21),
  ('result -> ci GUION PNUMERO PUNTOYCOMA','result',4,'p_result','parser_training.py',29),
  ('ci -> ci COMA PNUMERO DOSPUNTOS COEFICIENTE','ci',5,'p_ci','parser_training.py',35),
  ('ci -> PNUMERO DOSPUNTOS COEFICIENTE','ci',3,'p_ci','parser_training.py',36),
]
